site_name: Demo1 Site
site_url: https://danbrough.org/demo1
copyright: dan@danbrough.org 2024
theme:
  name: material
  theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences