
name: Test1 workflow

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Setup gradle
        uses: yumemi-inc/setup-java-gradle@v1
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: false

      - name: Setup gradle.properties
        shell: bash
        run: |
          echo XTRAS_DIR=$HOME/xtras >> $GITHUB_ENV
          GRADLE_PROPS=$HOME/.gradle/gradle.properties
          echo Configuring $GRADLE_PROPS 
          if [ -f $GRADLE_PROPS ]; then
            echo existing $GRADLE_PROPS
            cat $GRADLE_PROPS
          fi
          cat > $GRADLE_PROPS <<PROPS
          org.gradle.caching=true
          signing.key=${{ secrets.GPG_SIGNING_KEY }}
          signing.password=${{ secrets.GPG_SIGNING_PASSWORD }}
          sonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }}
          sonatype.username=${{ secrets.SONATYPE_USERNAME }}
          sonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          xtras.dir=$HOME/xtras
          PROPS
          chmod 600 $GRADLE_PROPS

      - name: Cache Xtras dir
        id: cache_xtras
        uses: actions/cache@v4.0.2
        with:
          path: ${{ env.XTRAS_DIR }}
          key: ${{ runner.os }}-xtras

      - name: publishAllPublicationsToXtras
        shell: bash
        run: ./gradlew publishAllPublicationsToXtras

          
